### ISSUE TITLE
QA_Artificial_Neural_Networks_Open_edx_Issue

### ISSUE THREAD

**Issue by sravanthimodepu** [virtual-labs/artificial-neural-networks-iiith#16]
Defect Description :
While testing this lab, found an issue in the open-edx, There is a button named "View unit in Studio" in all the pages of Course section, when we click on that it is redirecting to "Unable to connect" error page. Instead it should display the unit in openedx studio.

Actual Result :
While testing this lab, found an issue in the open-edx, when we click on "View unit in Studio" that it is redirecting to "Unable to connect" error page. Instead it should display the unit in openedx studio.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by BSravanthi** [comment]
Kept on hold after the discussion with Lalit.
