### ISSUE TITLE
QA_Artificial_Neural_Networks_Spelling_Mistakes

### ISSUE THREAD

**Issue by sravanthimodepu** [virtual-labs/artificial-neural-networks-iiith#17]
Defect Description :
While testing this lab, found spelling mistakes in the experiments 6, 7, 8, 9, 10 pages. There should not be any spelling mistakesin the pages.

Actual Result :
While testing this lab, found spelling mistakes in the experiments 6, 7, 8, 9, 10 pages. There should not be any spelling mistakes in the pages.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by BSravanthi** [comment]
Fixed
