### ISSUE TITLE
Newline tags missing between social media icons

### ISSUE THREAD

**Issue by nishant-sachdeva** [virtual-labs/artificial-neural-networks-iiith#179]
As per the code in the repository: 
The social media links in the contact section appear in the same line. But as per the actual website, they appear in separate lines. This counts as an issue.

SCREENSHOT:
![Screenshot from 2019-03-22 19-38-51](https://user-images.githubusercontent.com/32475507/54829450-6e62de00-4cdc-11e9-968f-18628b0bf74a.png)

Ideal fix: Add the newline tag between the social media icons

**Comment by nishant999sachdeva** [comment]
Fixed: 3ede041cbdded1c9ae5b1e159b4c02b53dddc7e0

**Comment by abhishek5460** [comment]
Validated-1 @nishant999sachdeva
