### ISSUE TITLE
QA_Artificial_Neural_Networks_Experiments

### ISSUE THREAD

**Issue by sravanthimodepu** [virtual-labs/artificial-neural-networks-iiith#19]
Defect Description :
While testing this lab, found an issue in the Experiments. As the lab has all the sections in one single html page, when we give the experiment link it is redirecting to the whole page of the lab. Instead it should redirect to the experiment page.

Actual Result :
While testing this lab, found an issue in the Experiments. Given link should redirect to the Experiment page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by BSravanthi** [comment]
As the lab is developed using php. Hence we are unable get the desired output.
