### ISSUE TITLE
QA_Artificial_Neural_Networks_Insonsistentcy_in_tables

### ISSUE THREAD

**Issue by sravanthimodepu** [virtual-labs/artificial-neural-networks-iiith#20]
Defect Description :
While testing this lab, found that there is an inconsistency whlie uploading the table. After uploading the table is exceeding the page, instead it should be inside the page.
Actual Result :
While testing this lab, found an issue in uploading the table. The table should be inside the page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by BSravanthi** [comment]
Fixed
